-- +goose Up
-- +goose StatementBegin

-- ── 1. visits table ───────────────────────────────────────────────────────────
CREATE TABLE visits (
    id            BIGSERIAL PRIMARY KEY,
    patient_id    BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    branch_id     BIGINT NOT NULL REFERENCES branches(id),
    visit_type    VARCHAR(20) NOT NULL DEFAULT 'scheduled'
                  CHECK (visit_type IN ('scheduled', 'walk_in')),
    status        VARCHAR(20) NOT NULL DEFAULT 'scheduled'
                  CHECK (status IN (
                      'scheduled',
                      'in_progress',
                      'completed',
                      'cancelled',
                      'no_show'
                  )),
    arrived_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    comment       TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_visits_patient_id  ON visits(patient_id);
CREATE INDEX idx_visits_branch_id   ON visits(branch_id);
CREATE INDEX idx_visits_status      ON visits(status);

-- ── 2. appointments: add visit_id and appointment_type ────────────────────────
ALTER TABLE appointments
    ADD COLUMN visit_id         BIGINT REFERENCES visits(id) ON DELETE SET NULL,
    ADD COLUMN appointment_type VARCHAR(20) NOT NULL DEFAULT 'scheduled'
                                CHECK (appointment_type IN ('scheduled', 'walk_in'));

CREATE INDEX idx_appointments_visit_id ON appointments(visit_id);

-- ── 3. Extend appointment status CHECK to include 'arrived' ──────────────────
ALTER TABLE appointments DROP CONSTRAINT appointments_status_check;
ALTER TABLE appointments ADD CONSTRAINT appointments_status_check
    CHECK (status IN (
        'created',
        'confirmed',
        'arrived',
        'cancelled_by_patient',
        'cancelled_by_admin',
        'completed',
        'no_show'
    ));

-- ── 4. Recreate GIST exclusion: add 'arrived'; exclude walk_in from blocking ──
--
-- Walk-in appointments have no reserved slot — they enter a queue.
-- Excluding appointment_type = 'walk_in' prevents false conflicts when
-- multiple walk-ins for the same doctor are registered at the same moment.
--
-- The existing constraint name is auto-generated by PostgreSQL; the canonical
-- name for this table/expression pattern is appointments_doctor_id_tstzrange_excl.
ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_doctor_id_tstzrange_excl;

ALTER TABLE appointments ADD CONSTRAINT appointments_doctor_id_tstzrange_excl
    EXCLUDE USING GIST (
        doctor_id WITH =,
        tstzrange(start_at, end_at) WITH &&
    ) WHERE (
        status IN ('created', 'confirmed', 'arrived')
        AND appointment_type = 'scheduled'
    );

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_doctor_id_tstzrange_excl;
ALTER TABLE appointments ADD CONSTRAINT appointments_doctor_id_tstzrange_excl
    EXCLUDE USING GIST (
        doctor_id WITH =,
        tstzrange(start_at, end_at) WITH &&
    ) WHERE (status IN ('created', 'confirmed'));

ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_status_check;
ALTER TABLE appointments ADD CONSTRAINT appointments_status_check
    CHECK (status IN (
        'created', 'confirmed', 'cancelled_by_patient',
        'cancelled_by_admin', 'completed', 'no_show'
    ));

ALTER TABLE appointments DROP COLUMN IF EXISTS appointment_type;
ALTER TABLE appointments DROP COLUMN IF EXISTS visit_id;

DROP TABLE IF EXISTS visits;

-- +goose StatementEnd
